### ISSUE TITLE
Can I build it for Spark 2.3.2 and Hive 3.1.0

### ISSUE THREAD

**Issue by SnchitGrover** [qubole/spark-acid#40]
Hi,

I would like to use this project for Spark 2.3.2 and Hive 3.1.0, 

1. Updated hive version inside shaded-dependency -> build.sbt 
(val hive_version = sys.props.getOrElse("hive.version", "3.1.0")
2. Updated spark version in build.sbt
(sparkVersion := sys.props.getOrElse("spark.version", "2.3.2"))

But my build is failing with below error:

> [info] Compiling 43 Scala sources and 6 Java sources to /Users/snchitg/Projects/spark-acid/target/scala-2.11/classes...
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:327: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Intersect in object Intersect
[error]         Intersect(left, right, isAll = true)
[error]                  ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:329: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Intersect in object Intersect
[error]         Intersect(left, right, isAll = false)
[error]                  ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:331: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Except in object Except
[error]         Except(left, right, isAll = true)
[error]               ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:333: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Except in object Except
[error]         Except(left, right, isAll = false)
[error]               ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:335: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Except in object Except
[error]         Except(left, right, isAll = true)
[error]               ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:337: too many arguments for method apply: (left: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan, right: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan)org.apache.spark.sql.catalyst.plans.logical.Except in object Except
[error]         Except(left, right, isAll = false)
[error]               ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:432: type mismatch;
[error]  found   : None.type
[error]  required: Seq[org.apache.spark.sql.catalyst.expressions.NamedExpression]
[error]     Pivot(None, pivotColumn, pivotValues, aggregates, query)
[error]           ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:432: type mismatch;
[error]  found   : scala.collection.mutable.Buffer[org.apache.spark.sql.catalyst.expressions.Expression]
[error]  required: Seq[org.apache.spark.sql.catalyst.expressions.Literal]
[error]     Pivot(None, pivotColumn, pivotValues, aggregates, query)
[error]                              ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:903: not found: value InSubquery
[error]         invertIfNotDefined(InSubquery(getValueExpressions(e), ListQuery(plan(ctx.query))))
[error]                            ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/catalyst/parser/AstBuilder.scala:1110: not found: value LambdaFunction
[error]     LambdaFunction(expression(ctx.expression), arguments)
[error]     ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/execution/SparkAcidSqlParser.scala:72: value setOpsPrecedenceEnforced is not a member of org.apache.spark.sql.internal.SQLConf
[error]     lexer.legacy_setops_precedence_enbled = SQLConf.get.setOpsPrecedenceEnforced
[error]                                                         ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/datasources/hiveacid/sql/execution/SparkAcidSqlParser.scala:79: value setOpsPrecedenceEnforced is not a member of org.apache.spark.sql.internal.SQLConf
[error]     parser.legacy_setops_precedence_enbled = SQLConf.get.setOpsPrecedenceEnforced
[error]                                                          ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/HiveAcidAutoConvert.scala:55: value resolveOperators is not a member of org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
[error]     plan resolveOperators {
[error]          ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/HiveAcidTable.scala:225: type mismatch;
[error]  found   : Seq[String]
[error]  required: Option[String]
[error]             x.withQualifier(hiveAcidMetadata.fullyQualifiedName.split('.').toSeq))
[error]                                                                            ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/HiveAcidTable.scala:169: non-variable type argument org.apache.spark.sql.Row in type pattern org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] (the underlying of org.apache.spark.sql.DataFrame) is unchecked since it is eliminated by erasure
[error]     val (df: DataFrame, qualifiedPlan: LogicalPlan, resolvedDf: DataFrame) = getResolvedReadDF
[error]              ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/HiveAcidTable.scala:169: non-variable type argument org.apache.spark.sql.Row in type pattern org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] (the underlying of org.apache.spark.sql.DataFrame) is unchecked since it is eliminated by erasure
[error]     val (df: DataFrame, qualifiedPlan: LogicalPlan, resolvedDf: DataFrame) = getResolvedReadDF
[error]                                                                 ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/HiveAcidTable.scala:324: non-variable type argument org.apache.spark.sql.Row in type pattern org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] (the underlying of org.apache.spark.sql.DataFrame) is unchecked since it is eliminated by erasure
[error]       val (_, qualifiedPlan: LogicalPlan, resolvedDf: DataFrame) = getResolvedReadDF
[error]                                                       ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/rdd/HiveAcidRDD.scala:286: overloaded method value addTaskCompletionListener with alternatives:
[error]   (f: org.apache.spark.TaskContext => Unit)org.apache.spark.TaskContext <and>
[error]   (listener: org.apache.spark.util.TaskCompletionListener)org.apache.spark.TaskContext
[error]  does not take type parameters
[error]       context.addTaskCompletionListener[Unit] { _ =>
[error]               ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala:64: type mismatch;
[error]  found   : Boolean(true)
[error]  required: org.apache.spark.sql.types.DataType
[error]         Seq(true, true))
[error]             ^
[error] /Users/snchitg/Projects/spark-acid/src/main/scala/com/qubole/spark/hiveacid/writer/hive/HiveAcidWriter.scala:64: type mismatch;
[error]  found   : Boolean(true)
[error]  required: org.apache.spark.sql.types.DataType
[error]         Seq(true, true))
[error]                   ^
[error] 20 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 19 s, completed 20 Apr 2020, 20:59:33

**Comment by abilng** [comment]
@SnchitGrover did you able to solve the issue ?

**Comment by SnchitGrover** [comment]
@abilng No it will not work with Spark 2.3.2 ver. We upgraded our Spark version to solve the problem.
